// Generated by prep_audio.py. System identities are deliberately absent.
const STIMULI = {
 "pref": [
  {
   "item": "J07",
   "spk": "J",
   "clips": {
    "X": "e499b018",
    "Y": "76ce224a"
   }
  },
  {
   "item": "J08",
   "spk": "J",
   "clips": {
    "X": "7290edb9",
    "Y": "2aec0df4"
   }
  },
  {
   "item": "J15",
   "spk": "J",
   "clips": {
    "X": "280e6b32",
    "Y": "25a68fc3"
   }
  },
  {
   "item": "J21",
   "spk": "J",
   "clips": {
    "X": "7e9dfcb5",
    "Y": "29ac207e"
   }
  },
  {
   "item": "J27",
   "spk": "J",
   "clips": {
    "X": "a2ca0c28",
    "Y": "79a77f62"
   }
  },
  {
   "item": "J34",
   "spk": "J",
   "clips": {
    "X": "5bf9ded1",
    "Y": "3e4dac8b"
   }
  },
  {
   "item": "J37",
   "spk": "J",
   "clips": {
    "X": "1c1a8884",
    "Y": "3a73bb9c"
   }
  },
  {
   "item": "J38",
   "spk": "J",
   "clips": {
    "X": "44b6796b",
    "Y": "e2857a0c"
   }
  },
  {
   "item": "J40",
   "spk": "J",
   "clips": {
    "X": "fb98f7ef",
    "Y": "051b125c"
   }
  },
  {
   "item": "J41",
   "spk": "J",
   "clips": {
    "X": "5ae2cf70",
    "Y": "9ef60169"
   }
  },
  {
   "item": "J43",
   "spk": "J",
   "clips": {
    "X": "7c339395",
    "Y": "c3642e6d"
   }
  },
  {
   "item": "J48",
   "spk": "J",
   "clips": {
    "X": "4c4488a6",
    "Y": "c22e74b5"
   }
  },
  {
   "item": "S01",
   "spk": "S",
   "clips": {
    "X": "d2ef7f97",
    "Y": "1eca228a"
   }
  },
  {
   "item": "S14",
   "spk": "S",
   "clips": {
    "X": "8921981a",
    "Y": "d0dc9847"
   }
  },
  {
   "item": "S17",
   "spk": "S",
   "clips": {
    "X": "10642203",
    "Y": "efc1d9af"
   }
  },
  {
   "item": "S21",
   "spk": "S",
   "clips": {
    "X": "f256fe6c",
    "Y": "e6bc81ea"
   }
  },
  {
   "item": "S23",
   "spk": "S",
   "clips": {
    "X": "c06ea2c6",
    "Y": "0ffb0b6e"
   }
  },
  {
   "item": "S25",
   "spk": "S",
   "clips": {
    "X": "c275e8dd",
    "Y": "e47526e1"
   }
  },
  {
   "item": "S26",
   "spk": "S",
   "clips": {
    "X": "eda9a9a2",
    "Y": "fdb226a4"
   }
  },
  {
   "item": "S32",
   "spk": "S",
   "clips": {
    "X": "967d09f7",
    "Y": "6359f012"
   }
  },
  {
   "item": "S33",
   "spk": "S",
   "clips": {
    "X": "4eb43f00",
    "Y": "53ffd0ca"
   }
  },
  {
   "item": "S42",
   "spk": "S",
   "clips": {
    "X": "d73de8c7",
    "Y": "221f2ff7"
   }
  },
  {
   "item": "S44",
   "spk": "S",
   "clips": {
    "X": "69d72f1f",
    "Y": "cc6be330"
   }
  },
  {
   "item": "S49",
   "spk": "S",
   "clips": {
    "X": "9a1d4e7c",
    "Y": "473576bb"
   }
  }
 ],
 "mos": [
  {
   "item": "J01",
   "spk": "J",
   "sys": "X",
   "file": "43f47919"
  },
  {
   "item": "J01",
   "spk": "J",
   "sys": "Y",
   "file": "ea16e1fb"
  },
  {
   "item": "J04",
   "spk": "J",
   "sys": "X",
   "file": "917bc1d0"
  },
  {
   "item": "J04",
   "spk": "J",
   "sys": "Y",
   "file": "59da113c"
  },
  {
   "item": "J06",
   "spk": "J",
   "sys": "X",
   "file": "93c9293a"
  },
  {
   "item": "J06",
   "spk": "J",
   "sys": "Y",
   "file": "a7ff97d2"
  },
  {
   "item": "J10",
   "spk": "J",
   "sys": "X",
   "file": "ad2aa5cd"
  },
  {
   "item": "J10",
   "spk": "J",
   "sys": "Y",
   "file": "7b60e4fa"
  },
  {
   "item": "J16",
   "spk": "J",
   "sys": "X",
   "file": "c3ca95c7"
  },
  {
   "item": "J16",
   "spk": "J",
   "sys": "Y",
   "file": "ecd18ee0"
  },
  {
   "item": "J29",
   "spk": "J",
   "sys": "X",
   "file": "aa6d8783"
  },
  {
   "item": "J29",
   "spk": "J",
   "sys": "Y",
   "file": "0bd0574c"
  },
  {
   "item": "J31",
   "spk": "J",
   "sys": "X",
   "file": "d79d4259"
  },
  {
   "item": "J31",
   "spk": "J",
   "sys": "Y",
   "file": "bf11e269"
  },
  {
   "item": "J32",
   "spk": "J",
   "sys": "X",
   "file": "b4e4fef4"
  },
  {
   "item": "J32",
   "spk": "J",
   "sys": "Y",
   "file": "17df2932"
  },
  {
   "item": "J42",
   "spk": "J",
   "sys": "X",
   "file": "4531bfe1"
  },
  {
   "item": "J42",
   "spk": "J",
   "sys": "Y",
   "file": "4fc9b68a"
  },
  {
   "item": "J46",
   "spk": "J",
   "sys": "X",
   "file": "1550d67c"
  },
  {
   "item": "J46",
   "spk": "J",
   "sys": "Y",
   "file": "763ef841"
  },
  {
   "item": "S05",
   "spk": "S",
   "sys": "X",
   "file": "b6a589b0"
  },
  {
   "item": "S05",
   "spk": "S",
   "sys": "Y",
   "file": "7e749741"
  },
  {
   "item": "S06",
   "spk": "S",
   "sys": "X",
   "file": "c2e1ba0f"
  },
  {
   "item": "S06",
   "spk": "S",
   "sys": "Y",
   "file": "c38d532a"
  },
  {
   "item": "S19",
   "spk": "S",
   "sys": "X",
   "file": "3a50ae03"
  },
  {
   "item": "S19",
   "spk": "S",
   "sys": "Y",
   "file": "5c256a86"
  },
  {
   "item": "S22",
   "spk": "S",
   "sys": "X",
   "file": "250c071f"
  },
  {
   "item": "S22",
   "spk": "S",
   "sys": "Y",
   "file": "a3399cf3"
  },
  {
   "item": "S29",
   "spk": "S",
   "sys": "X",
   "file": "1b5ea5ac"
  },
  {
   "item": "S29",
   "spk": "S",
   "sys": "Y",
   "file": "1aa2bcf1"
  },
  {
   "item": "S30",
   "spk": "S",
   "sys": "X",
   "file": "f00ad0ae"
  },
  {
   "item": "S30",
   "spk": "S",
   "sys": "Y",
   "file": "0e1014ba"
  },
  {
   "item": "S34",
   "spk": "S",
   "sys": "X",
   "file": "35fb457c"
  },
  {
   "item": "S34",
   "spk": "S",
   "sys": "Y",
   "file": "2be9b4e1"
  },
  {
   "item": "S35",
   "spk": "S",
   "sys": "X",
   "file": "bcc345a8"
  },
  {
   "item": "S35",
   "spk": "S",
   "sys": "Y",
   "file": "54648535"
  },
  {
   "item": "S38",
   "spk": "S",
   "sys": "X",
   "file": "3cdad637"
  },
  {
   "item": "S38",
   "spk": "S",
   "sys": "Y",
   "file": "5527cfa1"
  },
  {
   "item": "S46",
   "spk": "S",
   "sys": "X",
   "file": "004b4a42"
  },
  {
   "item": "S46",
   "spk": "S",
   "sys": "Y",
   "file": "05aac1a0"
  }
 ],
 "practice": {
  "item": "S41",
  "clips": {
   "X": "dc8c752e",
   "Y": "3ee509c2"
  }
 }
};
