// Generated by prep_audio_v2.py. Condition identities are deliberately absent.
const STIMULI = {
 "pref": [
  {
   "item": "J003",
   "spk": "J",
   "codes": [
    "Y",
    "Z"
   ],
   "clips": {
    "Y": "da106735",
    "Z": "749e163a"
   }
  },
  {
   "item": "J011",
   "spk": "J",
   "codes": [
    "Y",
    "Z"
   ],
   "clips": {
    "Y": "ff69b843",
    "Z": "e769f16e"
   }
  },
  {
   "item": "J017",
   "spk": "J",
   "codes": [
    "Y",
    "Z"
   ],
   "clips": {
    "Y": "b6b07995",
    "Z": "0a50247c"
   }
  },
  {
   "item": "J021",
   "spk": "J",
   "codes": [
    "Y",
    "X"
   ],
   "clips": {
    "Y": "afb5af19",
    "X": "1e516154"
   }
  },
  {
   "item": "J027",
   "spk": "J",
   "codes": [
    "Y",
    "X"
   ],
   "clips": {
    "Y": "bf60c622",
    "X": "3fc01610"
   }
  },
  {
   "item": "J029",
   "spk": "J",
   "codes": [
    "Y",
    "X"
   ],
   "clips": {
    "Y": "52ba76b0",
    "X": "aec954d9"
   }
  },
  {
   "item": "J008",
   "spk": "J",
   "codes": [
    "Z",
    "X"
   ],
   "clips": {
    "Z": "a5a11f79",
    "X": "b24ecde3"
   }
  },
  {
   "item": "J020",
   "spk": "J",
   "codes": [
    "Z",
    "X"
   ],
   "clips": {
    "Z": "110ffc90",
    "X": "155801f4"
   }
  },
  {
   "item": "J022",
   "spk": "J",
   "codes": [
    "Z",
    "X"
   ],
   "clips": {
    "Z": "b52845e3",
    "X": "8f91e209"
   }
  },
  {
   "item": "S000",
   "spk": "S",
   "codes": [
    "Y",
    "Z"
   ],
   "clips": {
    "Y": "23ef75f7",
    "Z": "a974c94b"
   }
  },
  {
   "item": "S008",
   "spk": "S",
   "codes": [
    "Y",
    "Z"
   ],
   "clips": {
    "Y": "e7b13a84",
    "Z": "e49f2373"
   }
  },
  {
   "item": "S026",
   "spk": "S",
   "codes": [
    "Y",
    "Z"
   ],
   "clips": {
    "Y": "b46436f3",
    "Z": "e397e306"
   }
  },
  {
   "item": "S002",
   "spk": "S",
   "codes": [
    "Y",
    "X"
   ],
   "clips": {
    "Y": "e04828db",
    "X": "88716375"
   }
  },
  {
   "item": "S003",
   "spk": "S",
   "codes": [
    "Y",
    "X"
   ],
   "clips": {
    "Y": "e7869301",
    "X": "5abda62c"
   }
  },
  {
   "item": "S010",
   "spk": "S",
   "codes": [
    "Y",
    "X"
   ],
   "clips": {
    "Y": "46bb22ae",
    "X": "3cc8a557"
   }
  },
  {
   "item": "S023",
   "spk": "S",
   "codes": [
    "Z",
    "X"
   ],
   "clips": {
    "Z": "7a6b6c60",
    "X": "11094f17"
   }
  },
  {
   "item": "S027",
   "spk": "S",
   "codes": [
    "Z",
    "X"
   ],
   "clips": {
    "Z": "4721b40b",
    "X": "13c6ad3e"
   }
  },
  {
   "item": "S029",
   "spk": "S",
   "codes": [
    "Z",
    "X"
   ],
   "clips": {
    "Z": "cb24a816",
    "X": "cac7d42e"
   }
  }
 ],
 "mos": [
  {
   "item": "J014",
   "spk": "J",
   "sys": "Y",
   "file": "0f878a97"
  },
  {
   "item": "J014",
   "spk": "J",
   "sys": "Z",
   "file": "c8965215"
  },
  {
   "item": "J014",
   "spk": "J",
   "sys": "X",
   "file": "3409c2da"
  },
  {
   "item": "J015",
   "spk": "J",
   "sys": "Y",
   "file": "2cd9d4b5"
  },
  {
   "item": "J015",
   "spk": "J",
   "sys": "Z",
   "file": "62318a98"
  },
  {
   "item": "J015",
   "spk": "J",
   "sys": "X",
   "file": "6c8bed04"
  },
  {
   "item": "J016",
   "spk": "J",
   "sys": "Y",
   "file": "554fb2b1"
  },
  {
   "item": "J016",
   "spk": "J",
   "sys": "Z",
   "file": "a1cd998f"
  },
  {
   "item": "J016",
   "spk": "J",
   "sys": "X",
   "file": "a3a70dd2"
  },
  {
   "item": "J018",
   "spk": "J",
   "sys": "Y",
   "file": "8040411b"
  },
  {
   "item": "J018",
   "spk": "J",
   "sys": "Z",
   "file": "5cc2b24e"
  },
  {
   "item": "J018",
   "spk": "J",
   "sys": "X",
   "file": "761363d8"
  },
  {
   "item": "J025",
   "spk": "J",
   "sys": "Y",
   "file": "5046d4b0"
  },
  {
   "item": "J025",
   "spk": "J",
   "sys": "Z",
   "file": "372bb819"
  },
  {
   "item": "J025",
   "spk": "J",
   "sys": "X",
   "file": "3a1f5c15"
  },
  {
   "item": "S006",
   "spk": "S",
   "sys": "Y",
   "file": "32932d7f"
  },
  {
   "item": "S006",
   "spk": "S",
   "sys": "Z",
   "file": "329be31a"
  },
  {
   "item": "S006",
   "spk": "S",
   "sys": "X",
   "file": "45f81078"
  },
  {
   "item": "S014",
   "spk": "S",
   "sys": "Y",
   "file": "58e25dc0"
  },
  {
   "item": "S014",
   "spk": "S",
   "sys": "Z",
   "file": "29dafe9e"
  },
  {
   "item": "S014",
   "spk": "S",
   "sys": "X",
   "file": "89627b4c"
  },
  {
   "item": "S017",
   "spk": "S",
   "sys": "Y",
   "file": "b253a2ac"
  },
  {
   "item": "S017",
   "spk": "S",
   "sys": "Z",
   "file": "761b41e8"
  },
  {
   "item": "S017",
   "spk": "S",
   "sys": "X",
   "file": "e6b500db"
  },
  {
   "item": "S019",
   "spk": "S",
   "sys": "Y",
   "file": "369c4c21"
  },
  {
   "item": "S019",
   "spk": "S",
   "sys": "Z",
   "file": "994a1db5"
  },
  {
   "item": "S019",
   "spk": "S",
   "sys": "X",
   "file": "bd4fb25c"
  },
  {
   "item": "S021",
   "spk": "S",
   "sys": "Y",
   "file": "7fa6df72"
  },
  {
   "item": "S021",
   "spk": "S",
   "sys": "Z",
   "file": "23a87be1"
  },
  {
   "item": "S021",
   "spk": "S",
   "sys": "X",
   "file": "9acbe507"
  }
 ],
 "practice": {
  "item": "S007",
  "codes": [
   "Y",
   "Z"
  ],
  "clips": {
   "Y": "1c4f5efe",
   "Z": "084b5302"
  }
 }
};
